### ISSUE TITLE
latgen faster speed improve

### ISSUE THREAD

**Issue by xfwu** [srvk/eesen#67]
Hi Yajie

Could you suggest some way to improve the speed of latgen-faster?
I tested some utterances in noisy environment, it could be extreamly slow (like > 10seconds).

I wonder if any parallel method can be applied here ( to speed up decoding for a single utterance)?

Best

**Comment by yajiemiao** [comment]
What is the real time factor for your decoding?

**Comment by xfwu** [comment]
Can I ask what do yo mean  by "real time factor"?

Best

**Comment by yajiemiao** [comment]
What is the length of the speech utterance you are trying to decode? How long does decoding take exactly?

**Comment by xfwu** [comment]
Hi Yajie

My utterance will up to 22 words length, for sentence like this, some are recorded in very noisy environment. I notice that for such utterance, it is more likely to use more than 10 seconds in the latgen-faster part. 
For sentence with similar length which recorded in a quieter place, it might only take 2-3 seconds.

But, for sentence of such length, is it realistic to expect better speed then 2-3 seconds?

Best

**Comment by yajiemiao** [comment]
Rather than use latgen-faster, you may use decode-faster to get the 1-best hypothesis directly.  This should speed up decoding. Refer to https://github.com/srvk/eesen/blob/master/asr_egs/wsj/steps/decode_ctc.sh

Also, reducing beam and max_active can also speed up decoding. But caution that this might hurt recognition accuracy.
