### ISSUE TITLE
setting the parameters

### ISSUE THREAD

**Issue by madhavsund** [srvk/eesen#75]
what would be the optimal values for decoding the digit corpus having only 10 words
--beam , --lattice_beam, --max-active, --acwt

any thumb rule i.e vocabulary size vs these parameters

**Comment by xfwu** [comment]
I am also interested to know, since in your case there is (almost) no language model's effect, I would suggest a bigger acwt.

both max-active(5000 by default) and beam (17 by default) can be smaller. But anyway,  to tune them on you own test set would be the best way.

Please let me know if I am wrong.

Best

**Comment by yajiemiao** [comment]
You can create a fake language model where each word (digit) has the probability of 1/10. Then the optimal acoustic weight will approximate what we normally use

**Comment by xfwu** [comment]
Can you please further explain that by  saying optimal aw, you mean 0.6 in the latgen-faster?
If I understand correctly, in the latgen-faster, acoustic_scale is only used after the lattice is generated (for applying fst::scaleLattice()). But why the acoustic_scale is not used in the decode() and GetRawLattice()?

Thank you very much

Best

**Comment by yajiemiao** [comment]
If you check https://github.com/srvk/eesen/blob/master/src/decoderbin/latgen-faster.cc, you can see that acoustic_scale is truly used in lattice generation
